import { BlockNumber } from '@polkadot/types/interfaces';
import { Compact, GenericExtrinsic } from '@polkadot/types';
import type { TxWithEvent } from '@polkadot/api-derive/types';
import type { AnyJson } from '@polkadot/types-codec/types';
import { BlockContext, ExtrinsicWithId, TxWithIdAndEvent } from './interfaces.js';

/**
 * A subclass of GenericExtrinsic that includes identifier information.
 */
export class GenericExtrinsicWithId extends GenericExtrinsic
  implements ExtrinsicWithId {
  blockNumber: Compact<BlockNumber>;
  blockPosition: number;

  constructor(
    value: GenericExtrinsic,
    {
      blockNumber,
      blockPosition
    } : BlockContext
  ) {
    super(value.registry, value.toU8a());
    this.blockNumber = blockNumber;
    this.blockPosition = blockPosition;
  }

  /**
   * Returns the unique identifier of the extrinsic.
   * The identifier is generated by combining the block number and the position of the extrinsic within the block.
   * The identifier follows the format `<block number>-<position>`, where:
   * - `<block number>` is the number of the block containing the extrinsic.
   * - `<position>` is the positional index of the extrinsic within the block, starting from 0.
   */
  get extrinsicId() {
    return `${this.blockNumber.toString()}-${this.blockPosition}`;
  }

  /**
   * Returns the JSON representation of the extrinsic with the added extrinsicId, blockNumber, and position properties.
   */
  toHuman(isExpanded?: boolean | undefined): AnyJson {
    return {
      extrinsicId: this.extrinsicId,
      blockNumber: this.blockNumber.toHuman(),
      position: this.blockPosition,
      ...(super.toHuman(isExpanded) as any)
    };
  }
}

/**
 * Enhances a transaction object with identifier information by wrapping the extrinsic with the GenericExtrinsicWithId class.
 * @param blockNumber The compact block number of the transaction.
 * @param blockPosition The position of the transaction within the block.
 * @param tx The transaction object to enhance.
 * @returns The enhanced transaction object with identifier information.
 */
export function enhanceTxWithId(
  context: BlockContext,
  tx: TxWithEvent
) : TxWithIdAndEvent {
  tx.extrinsic = new GenericExtrinsicWithId(tx.extrinsic, context);
  return tx as TxWithIdAndEvent;
}