/*
 * Copyright 2023 SO/DA zone - Marc Fornós & Xueying Wang
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { BlockNumber } from '@polkadot/types/interfaces';
import { Compact, GenericExtrinsic } from '@polkadot/types';
import type { TxWithEvent } from '@polkadot/api-derive/types';
import type { AnyJson, IU8a } from '@polkadot/types-codec/types';

import { ExtrinsicBlockContext, ExtrinsicWithId, TxWithIdAndEvent } from './interfaces.js';

/**
 * A subclass of GenericExtrinsic that includes identifier information.
 */
export class GenericExtrinsicWithId extends GenericExtrinsic
  implements ExtrinsicWithId {
  blockNumber: Compact<BlockNumber>;
  blockHash: IU8a;
  blockPosition: number;

  constructor(
    value: GenericExtrinsic,
    {
      blockNumber,
      blockPosition,
      blockHash
    } : ExtrinsicBlockContext
  ) {
    super(value.registry, value.toU8a());
    this.blockNumber = blockNumber;
    this.blockPosition = blockPosition;
    this.blockHash = blockHash;
  }

  /**
   * Returns the unique identifier of the extrinsic.
   * The identifier is generated by combining the block number and the position of the extrinsic within the block.
   * The identifier follows the format `<block number>-<position>`, where:
   * - `<block number>` is the number of the block containing the extrinsic.
   * - `<position>` is the positional index of the extrinsic within the block, starting from 0.
   */
  get extrinsicId() {
    return `${this.blockNumber.toString()}-${this.blockPosition}`;
  }

  /**
   * Returns the JSON representation of the extrinsic with the added extrinsicId, blockNumber, and position properties.
   */
  toHuman(isExpanded?: boolean | undefined): AnyJson {
    return {
      extrinsicId: this.extrinsicId,
      blockNumber: this.blockNumber.toHuman(),
      blockHash: this.blockHash.toHuman(),
      position: this.blockPosition,
      ...(super.toHuman(isExpanded) as any)
    };
  }
}

/**
 * Enhances a transaction object with identifier information by wrapping the extrinsic with the GenericExtrinsicWithId class.
 * @param context The extrinsic block context.
 * @param tx The transaction object to enhance.
 * @returns The enhanced transaction object with identifier information.
 */
export function enhanceTxWithId(
  context: ExtrinsicBlockContext,
  tx: TxWithEvent
) : TxWithIdAndEvent {
  tx.extrinsic = new GenericExtrinsicWithId(tx.extrinsic, context);
  return tx as TxWithIdAndEvent;
}